name: Test Build

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile.prod
          push: false
          tags: frontend:latest
