name: Test Build

on:
  # Triggers the workflow on push events
  push:
    branches [ main ]

  jobs:
    build_and_push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v2

        - name: Build image
          uses: docker build -t frontend .