import react from "react"
import { ReactComponent as privateIcon } from "../assets/roadmapDropdown_assets/private_icon.svg"
import { ReactComponent as publicIcon } from "../assets/roadmapDropdown_assets/public_icon.svg"
import { ReactComponent as deleteIcon } from "../assets/roadmapDropdown_assets/delete_icon.svg"
import { ReactComponent as renameIcon } from "../assets/roadmapDropdown_assets/rename_icon.svg"
import { ReactComponent as dropdownIcon } from "../assets/roadmapDropdown_assets/dropdown_icon.svg"